### ISSUE TITLE
دمج فورى الى تطبيق اندرويد

### ISSUE THREAD

**Issue by Ayman-SHaaban-ELsayed** [tawfik-s/fawry-camp-data#8]
انا مبرمج اندرويد،ارغب فى اضافة خدمات فورى الى تطبيق اندرويد جافا قائم بالفعل، هل يوجد رابط مشروع جاهز لمساعدتى فى اتمام هذه العملية
او فيديو؟

**Comment by tawfik-s** [comment]
hi Ayman this repo is for intern material not related to payment integration. try to contact fawry to solve your integration problem.

**Comment by Ayman-SHaaban-ELsayed** [comment]
أهلا توفيق ،هل لديك اى ادوات أو روابط للمساعدة مؤقتا؟
